# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vFsyCOAhCRuf-f9aFOOUhQa6DNKeMvx
"""

import pandas as pd
import streamlit as st

# App Config
st.set_page_config(page_title="Influencer Discovery Tool", layout="wide")

# Header Section
st.markdown("""
    <style>
        .title {
            font-size: 42px;
            font-weight: bold;
            color: #ff4b4b;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 10px;
        }
        .subtitle {
            text-align: center;
            font-size: 18px;
            margin-bottom: 30px;
        }
        .card {
            background-color: #f9f9f9;
            padding: 15px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        img.icon {
            width: 20px;
            vertical-align: middle;
            margin-right: 5px;
        }
    </style>
    <div class="title">Influencer Discovery Tool</div>
    <div class="subtitle">Explore top influencers across social media platforms</div>
""", unsafe_allow_html=True)

# Load data
df = pd.read_excel("cleaned_influencer_data (1) (1).xlsx")

# Dropdown for Influencer Tier
influencer_types = sorted(df['influencer_tier'].dropna().unique())
selected_type = st.selectbox("Select Influencer Tier", influencer_types)

# Filter data
filtered_df = df[df['influencer_tier'] == selected_type].sort_values(by='trending_score', ascending=False)

# Display influencers
if filtered_df.empty:
    st.warning("No influencers found for the selected tier.")
else:
    for _, row in filtered_df.iterrows():
        profile_image = row['youtube_profile_image'] if pd.notna(row['youtube_profile_image']) else ''
        name = row['youtube_name'] if pd.notna(row['youtube_name']) else row['instagram_username']
        insta_followers = row['instagram_followers'] if pd.notna(row['instagram_followers']) else ''
        yt_subs = row['subscribers'] if pd.notna(row['subscribers']) else ''
        trending_score = row['trending_score'] if pd.notna(row['trending_score']) else ''
        yt_views = row['total_views'] if pd.notna(row['total_views']) else ''
        video_link = row['top_video_link'] if pd.notna(row['top_video_link']) else ''
        country = row['country'] if pd.notna(row['country']) else ''
        insta_link = row['instagram_profile_link'] if pd.notna(row['instagram_profile_link']) else '#'
        yt_link = row['youtube_profile_link'] if pd.notna(row['youtube_profile_link']) else '#'
        industry = row['industry'] if pd.notna(row['industry']) else 'N/A'
        niche = row['niche'] if pd.notna(row['niche']) else 'N/A'

        st.markdown(f"""
        <div class="card">
            <div style="display: flex; align-items: center;">
                <div style="margin-right: 20px;">
                    <img src="{profile_image}" width="100" style="border-radius: 10px;">
                </div>
                <div>
                    <h4>{name}</h4>
                    <p><b>Industry:</b> {industry}</p>
                    <p><b>Niche:</b> {niche}</p>
                    <p><img class="icon" src="https://cdn-icons-png.flaticon.com/512/2111/2111463.png"> <b>Instagram Followers:</b> {insta_followers}</p>
                    <p><img class="icon" src="https://cdn-icons-png.flaticon.com/512/1384/1384060.png"> <b>YouTube Subscribers:</b> {yt_subs}</p>
                    <p><b>Trending Score:</b> {trending_score}</p>
                    <p><b>Total YouTube Views:</b> {yt_views}</p>
                    <p><b>Top YouTube Video:</b> <a href="{video_link}" target="_blank">Watch</a></p>
                    <p><b>Country:</b> {country}</p>
                    <p><a href="{insta_link}" target="_blank">Instagram</a> | <a href="{yt_link}" target="_blank">YouTube</a></p>
                </div>
            </div>
        </div>
        """, unsafe_allow_html=True)